<a href="https://colab.research.google.com/github/sadrac29/LAB-IA/blob/main/LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
! wget https://raw.githubusercontent.com/sadrac29/LAB-IA/main/Datos.csv

--2020-12-16 17:28:33--  https://raw.githubusercontent.com/sadrac29/LAB-IA/main/Datos.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28102 (27K) [text/plain]
Saving to: ‘Datos.csv.3’

Datos.csv.3         100%[===================>]  27.44K  --.-KB/s    in 0.003s

2020-12-16 17:28:33 (10.0 MB/s) - ‘Datos.csv.3’ saved [28102/28102]

In [23]:
import pandas as pd
data = pd.read_csv("Datos.csv.3")
data

     Numero  ... vivienda nueva /vivienda de segunda
0         2  ...                                 2.0
1         2  ...                                 1.0
2         2  ...                                 2.0
3         1  ...                                 2.0
4         1  ...                                 2.0
..      ...  ...                                 ...
370       4  ...                                 2.0
371       4  ...                                 1.0
372       4  ...                                 1.0
373       4  ...                                 2.0
374       4  ...                                 1.0

[375 rows x 11 columns]

In [15]:
! wget https://raw.githubusercontent.com/sadrac29/LAB-IA/main/Datos2.csv

--2020-12-16 17:25:13--  https://raw.githubusercontent.com/sadrac29/LAB-IA/main/Datos2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 812 [text/plain]
Saving to: ‘Datos2.csv’

Datos2.csv          100%[===================>]     812  --.-KB/s    in 0s

2020-12-16 17:25:14 (49.4 MB/s) - ‘Datos2.csv’ saved [812/812]

In [16]:
import pandas as pd
import numpy as np

data2 = pd.read_csv("Datos2.csv")
data2

    usuarios   salarios
0           1       2369
1           2       2308
2           3       2669
3           4       2699
4           5       1851
..        ...        ...
95         96       2540
96         97       2436
97         98       2540
98         99       2803
99        100       2105

[100 rows x 2 columns]

In [24]:
from random import choice
descuento = (data2['salarios '] * 0.4)
#print (descuento)
u_aleatorio = choice(descuento)

In [25]:
ICN = 0.055/12
ICV = 0.015/12

In [26]:
precioVenta= data['precio de Venta']
#print (precioVenta)

In [29]:
len(data['vivienda nueva /vivienda de segunda'])
import math
import numpy as np
vec = []
for pos, estado in enumerate(data['vivienda nueva /vivienda de segunda']):
 
  if estado == 2.0:
    de = (ICV * precioVenta[pos])
    nu1 = 1+ICV
    nu = (1 - math.pow((nu1),-360)) 
    p = round(de/nu)
    vec.append(p)
   # vec=np.array(p)
    #print("Valor 2.0 ==> {}".format(p))
  else:
    de = (ICN * precioVenta[pos])
    nu1 = 1+ICN
    nu = 1 - math.pow((nu1),-360)  
    p1 = round(de/nu)
    vec.append(p1)
   # vec=np.array(p1)
    #print("valor 1.0 ==> {}".format(p1))

In [30]:

print('Usuario seleccionado: ')
print(round(u_aleatorio))

Usuario seleccionado:
910.0

In [31]:
df=pd.DataFrame(data)
comparacion = []
for i in range(374):
 if vec[i] <= u_aleatorio:
   print(df.iloc[i])
   print('')
   comparacion.append(vec[i])

Numero                                            2
Ubicación                                 Calidonia
Nombre                                        WHITE
Disponibilidad                                VENTA
precio de Venta                              250000
Precio de Alquiler                              NaN
Recamaras                                         2
Baños                                             2
Dimensión                                       119
Tipo de vivienda                       APARTAMENTOS
vivienda nueva /vivienda de segunda               2
Name: 0, dtype: object

Numero                                            2
Ubicación                                 Calidonia
Nombre                                     BAYFRONT
Disponibilidad                                VENTA
precio de Venta                              215000
Precio de Alquiler                              NaN
Recamaras                                         1
Baños                                             1
Dimensión                                       100
Tipo de vivienda                       APARTAMENTOS
vivienda nueva /vivienda de segunda               2
Name: 5, dtype: object

Numero                                              2
Ubicación                                   Calidonia
Nombre                                 BAYFRONT TOWER
Disponibilidad                                  VENTA
precio de Venta                                220000
Precio de Alquiler                                NaN
Recamaras                                           1
Baños                                               1
Dimensión                                          87
Tipo de vivienda                         APARTAMENTOS
vivienda nueva /vivienda de segunda                 2
Name: 16, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                                     OCEANAIRE
Disponibilidad                                                 VENTA
precio de Venta                                               218000
Precio de Alquiler                                               NaN
Recamaras                                                          1
Baños                                                              1
Dimensión                                                         95
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 27, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                           PH Oasis on the Bay
Disponibilidad                                                 VENTA
precio de Venta                                               225000
Precio de Alquiler                                               NaN
Recamaras                                                          2
Baños                                                              1
Dimensión                                                        199
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 28, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                                 ROYAL PACIFIC
Disponibilidad                                                 VENTA
precio de Venta                                               260000
Precio de Alquiler                                               NaN
Recamaras                                                          3
Baños                                                              2
Dimensión                                                        144
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 29, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                                COURTYARD VIEW
Disponibilidad                                                 VENTA
precio de Venta                                               225000
Precio de Alquiler                                               NaN
Recamaras                                                          2
Baños                                                              2
Dimensión                                                        160
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 31, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                                         OASIS
Disponibilidad                                                 VENTA
precio de Venta                                               210000
Precio de Alquiler                                               NaN
Recamaras                                                          2
Baños                                                              1
Dimensión                                                         99
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 38, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                           COSTA PACIFICA T100
Disponibilidad                                                 VENTA
precio de Venta                                               249000
Precio de Alquiler                                               NaN
Recamaras                                                          3
Baños                                                              2
Dimensión                                                        242
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 40, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                              OASIS ON THE BAY
Disponibilidad                                          VENTALQUILER
precio de Venta                                               220000
Precio de Alquiler                                               NaN
Recamaras                                                          2
Baños                                                              1
Dimensión                                                         99
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 59, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                     COSTA PACIFICA TORRE T100
Disponibilidad                                                 VENTA
precio de Venta                                               240000
Precio de Alquiler                                               NaN
Recamaras                                                          3
Baños                                                              3
Dimensión                                                        126
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 60, dtype: object

Numero                                                             5
Ubicación                              Punta Pacifica, San francisco
Nombre                                                  PACIFIC BLUE
Disponibilidad                                                 VENTA
precio de Venta                                               190000
Precio de Alquiler                                               NaN
Recamaras                                                          2
Baños                                                              2
Dimensión                                                         88
Tipo de vivienda                                        APARTAMENTOS
vivienda nueva /vivienda de segunda                                2
Name: 70, dtype: object

Numero                                            1
Ubicación                               Bella Vista
Nombre                                        WHITE
Disponibilidad                                VENTA
precio de Venta                              250000
Precio de Alquiler                              NaN
Recamaras                                         2
Baños                                             2
Dimensión                                       119
Tipo de vivienda                       APARTAMENTOS
vivienda nueva /vivienda de segunda               2
Name: 84, dtype: object

Numero                                            2
Ubicación                                 Calidonia
Nombre                                     BAYFRONT
Disponibilidad                                VENTA
precio de Venta                              215000
Precio de Alquiler                              NaN
Recamaras                                         1
Baños                                             1
Dimensión                                       100
Tipo de vivienda                       APARTAMENTOS
vivienda nueva /vivienda de segunda               2
Name: 89, dtype: object

Numero                                              2
Ubicación                                   Calidonia
Nombre                                 BAYFRONT TOWER
Disponibilidad                                  VENTA
precio de Venta                                220000
Precio de Alquiler                                NaN
Recamaras                                           1
Baños                                               1
Dimensión                                          87
Tipo de vivienda                         APARTAMENTOS
vivienda nueva /vivienda de segunda                 2
Name: 100, dtype: object

Numero                                                    6
Ubicación                              Obarrio, Bella Vista
Nombre                                    PH BRISAS OBARRIO
Disponibilidad                                        VENTA
precio de Venta                                      240000
Precio de Alquiler                                      NaN
Recamaras                                                 3
Baños                                                     3
Dimensión                                               173
Tipo de vivienda                               APARTAMENTOS
vivienda nueva /vivienda de segunda                       2
Name: 110, dtype: object

Numero                                                    6
Ubicación                              Obarrio, Bella Vista
Nombre                                           RIVER PARK
Disponibilidad                                        VENTA
precio de Venta                                      240000
Precio de Alquiler                                      NaN
Recamaras                                                 3
Baños                                                     2
Dimensión                                               131
Tipo de vivienda                               APARTAMENTOS
vivienda nueva /vivienda de segunda                       2
Name: 111, dtype: object

Numero                                                                  6
Ubicación                                            Obarrio, Bella Vista
Nombre                                 Vendo ganga apto amueblado Obarrio
Disponibilidad                                                      VENTA
precio de Venta                                                    230000
Precio de Alquiler                                                    NaN
Recamaras                                                               3
Baños                                                                   3
Dimensión                                                             150
Tipo de vivienda                                             APARTAMENTOS
vivienda nueva /vivienda de segunda                                     2
Name: 112, dtype: object

Numero                                                    6
Ubicación                              Obarrio, Bella Vista
Nombre                                            PH Denovo
Disponibilidad                                        VENTA
precio de Venta                                      205000
Precio de Alquiler                                      NaN
Recamaras                                                 2
Baños                                                     2
Dimensión                                               110
Tipo de vivienda                               APARTAMENTOS
vivienda nueva /vivienda de segunda                       2
Name: 115, dtype: object

Numero                                                         1
Ubicación                                            Bella Vista
Nombre                                 Apartamento en Yacht Club
Disponibilidad                                             VENTA
precio de Venta                                           261670
Precio de Alquiler                                           NaN
Recamaras                                                      1
Baños                                                          1
Dimensión                                                    166
Tipo de vivienda                                    APARTAMENTOS
vivienda nueva /vivienda de segunda                            2
Name: 122, dtype: object

Numero                                            1
Ubicación                               Bella Vista
Nombre                                 THE SEAWAVES
Disponibilidad                                VENTA
precio de Venta                              220000
Precio de Alquiler                              NaN
Recamaras                                         3
Baños                                             2
Dimensión                                       125
Tipo de vivienda                       APARTAMENTOS
vivienda nueva /vivienda de segunda               2
Name: 124, dtype: object

Numero                                                                       1
Ubicación                                                          Bella Vista
Nombre                                 MEGAPOLIS PISO ALTO | EVALUAMOS OFERTAS
Disponibilidad                                                           VENTA
precio de Venta                                                         101000
Precio de Alquiler                                                         NaN
Recamaras                                                                    1
Baños                                                                        1
Dimensión                                                                   43
Tipo de vivienda                                                  APARTAMENTOS
vivienda nueva /vivienda de segunda                                          2
Name: 129, dtype: object

Numero                                              7
Ubicación                              Costa del Este
Nombre                                   Sol del Este
Disponibilidad                                  VENTA
precio de Venta                                260000
Precio de Alquiler                                NaN
Recamaras                                           3
Baños                                               3
Dimensión                                         147
Tipo de vivienda                         APARTAMENTOS
vivienda nueva /vivienda de segunda                 2
Name: 147, dtype: object

Numero                                                 7
Ubicación                                 Costa del Este
Nombre                                 Green Bay III 22B
Disponibilidad                                     VENTA
precio de Venta                                   165000
Precio de Alquiler                                   NaN
Recamaras                                              3
Baños                                                  2
Dimensión                                            114
Tipo de vivienda                            APARTAMENTOS
vivienda nueva /vivienda de segunda                    2
Name: 154, dtype: object

Numero                                                     7
Ubicación                                     Costa del Este
Nombre                                 PH SEVILLA T0RRE 1000
Disponibilidad                                         VENTA
precio de Venta                                       239000
Precio de Alquiler                                       NaN
Recamaras                                                  2
Baños                                                      2
Dimensión                                                110
Tipo de vivienda                                APARTAMENTOS
vivienda nueva /vivienda de segunda                        2
Name: 168, dtype: object

Numero                                                7
Ubicación                                Costa del Este
Nombre                                 Sol del Este 19A
Disponibilidad                             VENTALQUILER
precio de Venta                                  260000
Precio de Alquiler                                 1400
Recamaras                                             3
Baños                                                 3
Dimensión                                           147
Tipo de vivienda                           APARTAMENTOS
vivienda nueva /vivienda de segunda                   2
Name: 178, dtype: object

Numero                                                        7
Ubicación                                        Costa del Este
Nombre                                 GREEN BAY COSTA DEL ESTE
Disponibilidad                                            VENTA
precio de Venta                                          180000
Precio de Alquiler                                          NaN
Recamaras                                                     3
Baños                                                         2
Dimensión                                                   125
Tipo de vivienda                                   APARTAMENTOS
vivienda nueva /vivienda de segunda                           2
Name: 184, dtype: object

Numero                                                        8
Ubicación                              Costa del Este,Juan Díaz
Nombre                                                  Sevilla
Disponibilidad                                     VENTALQUILER
precio de Venta                                          220000
Precio de Alquiler                                         1200
Recamaras                                                     2
Baños                                                         2
Dimensión                                                   110
Tipo de vivienda                                   APARTAMENTOS
vivienda nueva /vivienda de segunda                           2
Name: 193, dtype: object

Numero                                                        8

In [34]:
import csv
ruta = 'Datos.csv.3'
with open(ruta, newline='',encoding='utf-8') as f:
  c = csv.DictReader(f)
  for r in c:
    print(r['Nombre'])

WHITE
H2O
WHITE
RIVAGE
WATERS ON THE BAY
BAYFRONT
LA ENSENADA
RIVAGE
MIRAMAR TORRE 2
MIRAMAR PLAZA
RIVAGE
ARTS & YOO
MIRAMAR TORRE 2
MIRAMAR TORRE 2
WATERS ON THE BAY
YOO
BAYFRONT TOWER
YOO
YOO
YACHT CLUB
YACHT CLUB
RIVAGE
WATERS ON THE BAY
WHITE
MIRAMAR TORRE 2
WHITE
Apartamento JW Marriott
OCEANAIRE
PH Oasis on the Bay
ROYAL PACIFIC
Aquamare 29-B
COURTYARD VIEW
AQUALINA
DUPONT TOWER
MYSTIC POINT
MYSTIC POINT T100
Punta Roca
COSTA PACIFICA T100
OASIS
AQUALINA
COSTA PACIFICA T100
BLUE BAHIA
BLUE BAHIA
DUPONT TOWER
OCEANAIRE
PH Oceanaire
SEMI-AMOBLADO + DEPÓSITO DE 11 METROS
AQUALINA
COSTA PACIFICA T100
COSTA PACIFICA T400
BLUE BAHIA, Distinguido ! Impecable !
PACIFIC STAR
PACIFIC POINT TORRE 300
OCEANAIRE
OCEAN PARK TORRE 1
LOFT FOUR 41
OCEAN DRIVE
COSTA PACIFICA T400
OCEAN DRIVE
OASIS ON THE BAY
COSTA PACIFICA TORRE T100
PACIFIC POINT TORRE 300
PACIFIC POINT TORRE 700
GRAND TOWER
TRUMP OCEAN CLUB
TRUMP OCEAN CLUB
OCEAN DRIVE
PACIFIC POINT TORRE 200
TRUMP OCEAN CLUB
OCEAN DRIVE
PACIFIC BLUE
ROYAL PACIFIC
PACIFIC POINT
PACIFIC POINT TORRE 300
OCEAN PARK TORRE 2
PACIFIC SKY
GRAND TOWER
GRAND TOWER
GRAND TOWER
Q TOWER
AQUAMARE
DUPONT TOWER
AQUAMARE
OCEAN PARK TORRE 1
WHITE
H2O
WHITE
RIVAGE
WATERS ON THE BAY
BAYFRONT
LA ENSENADA
RIVAGE
MIRAMAR TORRE 2
MIRAMAR PLAZA
RIVAGE
ARTS & YOO
MIRAMAR TORRE 2
MIRAMAR TORRE 2
WATERS ON THE BAY
YOO
BAYFRONT TOWER
YOO
YOO
YACHT CLUB
YACHT CLUB
RIVAGE
WATERS ON THE BAY
WHITE
MIRAMAR TORRE 2
WHITE
PH BRISAS OBARRIO
RIVER PARK
Vendo ganga apto amueblado Obarrio
CASA EN OBARRIO PARA REMODELAR $ 400,000
EXCELENTE APARTAMENTO EN OBARRIO
PH Denovo
SOPHIA TOWER
CASA EN OBARRIO
SOPHIA TOWER
THE PALM
THE PALM
RIVER PARK
Apartamento en Yacht Club
ESCUCHAMOS OFERTAS ¡PRECIO NEGOCIABLE!
THE SEAWAVES
CERROMAR
Apartamento en PH Marina Park
Miramar 36-B
SE VENDE APARTAMENTO EN PH ALLURE
MEGAPOLIS PISO ALTO | EVALUAMOS OFERTAS
ph h2o on the ocean
Torres del Pacifico Torre B
NUOVO PANAMA con 4 ESTACIONAMIENTOS
NUOVO PANAMA con 2 ESTACIONAMIENTOS
Apartamento en venta PH Rivage 29-B
NUOVO PANAMA A PASOS DE LA CINTA COSTERA
ROR
CASA COMERCIAL EN BELLA VISTA
P.H BELLA VISTA PARK,
PH BELLA VISTA PARK
ROR
ROR
BELLE VIEW
Parkside Costa del Este
MAREA II
COSTA SERENA
Castellammare Loft
Sol del Este
COSTA SERENA
Costa Dorada #82
Costa del Este, COSTA SERENA
COSTA AZUL
Costa Serena
OCEAN ONE
Green Bay III 22B
COSTA SERENA
COSTA BAY
RIVERSIDE
BALMORAL
CAMELIAS
BEGONIAS
PH ALTAMAR DEL ESTE
PH RIVERSIDE EN ALQUILER O VENTA
COSTA BELLA RESIDENCIA EN VENTA
MAREA II
PH VITRI TOWER
SOHO TOWER IMPECABLE
COUNTRY CLUB
PH SEVILLA T0RRE 1000
TORRE ZEUS
COSTA SERENA
PARQUE DEL MAR I
TOSCANA DEL ESTE
ROYAL PACIFIC
OCEAN TWO
PH Breeze
PH MAREA
OCEAN TWO
Sol del Este 19A
PH MAREA
PH PARQUE DEL MAR LINDA VISTA AL PARQUE
OCEAN TWO
PANAMA BAY TOWER
VITRI TOWER
GREEN BAY COSTA DEL ESTE
Ocean Two
Riverside
Penthouse Breeze Costa del Este
TEN TOWER
Casa
Parque del Mar
PH – Pearl At The Sea
PARKSIDE
Sevilla
LATITUDE
PH TITANIUM
Royal Pacific
MURANO
TEN TOWER
TOSCANA DEL ESTE
BALMORAL
THE REGENT COUNTRY CLUB
THE REGENT COUNTRY CLUB
MAREA II
MAREA II
MAREA II
MAREA I
PALMERAS DEL ESTE
ACQUA I
MAREA II
ACQUA I
TOP TOWERS
TITANIUM
PARQUE DEL MAR I
MAGNOLIAS
COSTA VIEW
MURANO
COSTA DE LAS PERLAS
TOP TOWERS
MAGNOLIAS
COSTA AZUL
BEGONIAS
BALMORAL
VERTIKAL
TITANIUM
ACQUA II
BREEZE
SOL DEL ESTE TORRE 1
SEVILLA
MAGNOLIAS
PALMERAS DEL ESTE
PEARL AT THE SEA
BREEZE
ELEVATION
COSTA DEL ESTE COUNTRY CLUB T100
SOL DEL ESTE TORRE 2
PARQUE DEL MAR I
PARQUE DEL MAR I
ACQUA II
PH PRIVILEDGE
THE HERITAGE
THE RESERVE T300
THE RESERVE T300
BUENAVISTA RESIDENCES
LA VISTA ON THE GREEN
LA VISTA ON THE GREEN
THE RESERVE T300
VALERY POINT
THE HERITAGE
EBBELLE
SOL MARINA REMODELADO – 242M2
Marbella Tower
PH Girasol
Apartamento en Marbella, Ph Alfil
PH LOS DELFINES APT 36
Grand Bay 2 recámaras
BAHIA ESMERALDA
Luxury apartment in Yoo Panama
TORRE MARBELLA
BAHIA ESMERALDA
BAHIA ESMERALDA
RIO MAR
COSTA DEL MAR
MARBELLA 47
MARBELLA TOWER II
MARBELLA TOWER II
PANAMAR
ICON TOWER
SOBRE LAS ROCAS
PUNTARENAS
Panamar Apt 2 A
SANTORINI
P.H. OCEAN SKY EN VENTA PISO COMPLETO
OCEAN SKY
DA VINCI
APARTAMENTO EN OCEAN SKY COCO DEL MAR
Edificio Panamar
PUNTARENAS
BOUTIQUE QUARTIER DEL MAR
CASA EN COCO DEL MAR
SANTORINI
VERANDA TOWER
ICON TOWER
BALEARES
BELVEDERE
EMBASSY CLUB COURTYARD II
TOWNHOUSE EMBASSY CLUB
Greenfield Casa 18
CASA EN CLAYTON
CLAYTON PARK
EMBASSY CLUB COURTYARD II
THE REGENT
PLAZA REAL
LAS MARQUESAS
PH Joy Tower
PH COUNTRY PARK
Aquamarina
ALQUILADO Y GENERANDO INGRESOS MENSUAL
PREMIER LOFT
7400 EAST
THE VIEW
DIAMOND TOWER
PH TERRASOL
LOS FLAMINGOS
Ph Cabomarzo
PREMIER LOFT
San Francisco Bay 26-B
Concept
Bah¡a Pac¡fica
San Francisco Bay T400
WATERFALLS
Apartamento en Torres de San Francisco
SAN FRANCISCO BAY T100
THE TOWERS T100
PH The Regent
BUGANVILLA
Terrawind torre 1000
DIAGONAL AL CENTRO COMERCIAL MULTIPLAZA
PH Sky Blue
APARTAMENTO EN SAN FRANCISCO 67
PH HARMONY TOWER
Terrawind
VENTA
HARMONY TOWER
STAR BAY
INFINITY TOWER
Casa San Francisco # 46
COCINA ESTILO AMERICANA | PUNTA PACIFICA
PACIFIC BAY
PARK LOFT
Mandarin Bay 30-A
PH GENESIS TOWER
STAR BAY
THE REGENT
THE REGENT
INFINITY TOWER
Aquamarina
PH TERRAWIND
PH TERRAWIND
SAN FRANCISCO 67
SERENITY AT THE BAY
MARINA PLAZA
SAN FRANCISCO BAY T100
THE REGENT
FAIRMONT PLAZA
MONTEMAR
PREMIUM TOWER
WATERFALLS
WINDOW TOWER
PACIFIC WIND
MONTEMAR
PLAZA MARINA
CASA EN SAN FRANCISCO
TERRAWIND TORRE 1000
TERRAWIND TORRE 2000
PARK LOFT
CAPRICE
PREMIER LOFT
JOY
PREMIER LOFT
THE COSMOPOLITAN
CASA EN SAN FRANCISCO
STAR BAY
KOLOSAL TOWER
PREMIUM TOWER
PREMIER LOFT
SERENITY
SERENITY
JOY
JOY
PLAZA REAL
PREMIUM TOWER
PACIFIC BAY
LATORRACA
TERRAZAS DEL PACIFICO

In [35]:
len(comparacion)

68

In [36]:
comparacion

[863.0,
 742.0,
 759.0,
 752.0,
 777.0,
 897.0,
 777.0,
 725.0,
 859.0,
 759.0,
 828.0,
 656.0,
 863.0,
 742.0,
 759.0,
 828.0,
 828.0,
 794.0,
 707.0,
 903.0,
 759.0,
 349.0,
 897.0,
 569.0,
 825.0,
 897.0,
 621.0,
 759.0,
 846.0,
 897.0,
 777.0,
 777.0,
 777.0,
 897.0,
 897.0,
 880.0,
 759.0,
 794.0,
 449.0,
 552.0,
 621.0,
 828.0,
 862.0,
 652.0,
 725.0,
 431.0,
 526.0,
 759.0,
 759.0,
 656.0,
 683.0,
 618.0,
 790.0,
 466.0,
 742.0,
 825.0,
 893.0,
 828.0,
 621.0,
 887.0,
 552.0,
 894.0,
 552.0,
 569.0,
 858.0,
 642.0,
 687.0,
 897.0]